server.port: 8090
#logging.level:
#  root: TRACE
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://auth.lanxinpay.com/auth/realms/pm
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: pm-app
            client-secret: 0711ad1d-9053-4e3a-a6bb-db2b783e8eee
            scope: openid
  cloud:
    gateway:
      routes:
        - id: pm-api
          uri: http://pm-resource-server
          predicates:
            - Host=pm.lanxinpay.com
            - Path=/api/**
          filters:
            - OAuthApi
        - id: pm-app
          uri: http://pm-web-app
          predicates:
            - Host=pm.lanxinpay.com
            - Method=GET
          filters:
            - name: OAuth
              args:
                staticPaths: /*.js,/*.css,/*.icon,/*.svg